server:
  port: 9090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_elder?serverTimezone=GMT%2b8
    username: root
    password: root@XH2001!
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB

mybatis-plus:
  mapper-locations: classpath:mapper/*/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

knife4j:
  enable: true
  setting:
    language: zh_cn


